# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/int_maby/Documents/cpp_mobica/cpp_training

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/int_maby/Documents/cpp_mobica/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/int_maby/Documents/cpp_mobica/build/CMakeFiles /home/int_maby/Documents/cpp_mobica/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/int_maby/Documents/cpp_mobica/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hello_world

# Build rule for target.
hello_world: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello_world
.PHONY : hello_world

# fast build rule for target.
hello_world/fast:
	$(MAKE) -f CMakeFiles/hello_world.dir/build.make CMakeFiles/hello_world.dir/build
.PHONY : hello_world/fast

#=============================================================================
# Target rules for targets named exercise_base

# Build rule for target.
exercise_base: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exercise_base
.PHONY : exercise_base

# fast build rule for target.
exercise_base/fast:
	$(MAKE) -f CMakeFiles/exercise_base.dir/build.make CMakeFiles/exercise_base.dir/build
.PHONY : exercise_base/fast

#=============================================================================
# Target rules for targets named module01

# Build rule for target.
module01: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 module01
.PHONY : module01

# fast build rule for target.
module01/fast:
	$(MAKE) -f CMakeFiles/module01.dir/build.make CMakeFiles/module01.dir/build
.PHONY : module01/fast

#=============================================================================
# Target rules for targets named module02

# Build rule for target.
module02: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 module02
.PHONY : module02

# fast build rule for target.
module02/fast:
	$(MAKE) -f CMakeFiles/module02.dir/build.make CMakeFiles/module02.dir/build
.PHONY : module02/fast

hello.o: hello.cpp.o

.PHONY : hello.o

# target to build an object file
hello.cpp.o:
	$(MAKE) -f CMakeFiles/hello_world.dir/build.make CMakeFiles/hello_world.dir/hello.cpp.o
.PHONY : hello.cpp.o

hello.i: hello.cpp.i

.PHONY : hello.i

# target to preprocess a source file
hello.cpp.i:
	$(MAKE) -f CMakeFiles/hello_world.dir/build.make CMakeFiles/hello_world.dir/hello.cpp.i
.PHONY : hello.cpp.i

hello.s: hello.cpp.s

.PHONY : hello.s

# target to generate assembly for a file
hello.cpp.s:
	$(MAKE) -f CMakeFiles/hello_world.dir/build.make CMakeFiles/hello_world.dir/hello.cpp.s
.PHONY : hello.cpp.s

module01_1.o: module01_1.cpp.o

.PHONY : module01_1.o

# target to build an object file
module01_1.cpp.o:
	$(MAKE) -f CMakeFiles/module01.dir/build.make CMakeFiles/module01.dir/module01_1.cpp.o
.PHONY : module01_1.cpp.o

module01_1.i: module01_1.cpp.i

.PHONY : module01_1.i

# target to preprocess a source file
module01_1.cpp.i:
	$(MAKE) -f CMakeFiles/module01.dir/build.make CMakeFiles/module01.dir/module01_1.cpp.i
.PHONY : module01_1.cpp.i

module01_1.s: module01_1.cpp.s

.PHONY : module01_1.s

# target to generate assembly for a file
module01_1.cpp.s:
	$(MAKE) -f CMakeFiles/module01.dir/build.make CMakeFiles/module01.dir/module01_1.cpp.s
.PHONY : module01_1.cpp.s

module01_2.o: module01_2.cpp.o

.PHONY : module01_2.o

# target to build an object file
module01_2.cpp.o:
	$(MAKE) -f CMakeFiles/module01.dir/build.make CMakeFiles/module01.dir/module01_2.cpp.o
.PHONY : module01_2.cpp.o

module01_2.i: module01_2.cpp.i

.PHONY : module01_2.i

# target to preprocess a source file
module01_2.cpp.i:
	$(MAKE) -f CMakeFiles/module01.dir/build.make CMakeFiles/module01.dir/module01_2.cpp.i
.PHONY : module01_2.cpp.i

module01_2.s: module01_2.cpp.s

.PHONY : module01_2.s

# target to generate assembly for a file
module01_2.cpp.s:
	$(MAKE) -f CMakeFiles/module01.dir/build.make CMakeFiles/module01.dir/module01_2.cpp.s
.PHONY : module01_2.cpp.s

module01_3.o: module01_3.cpp.o

.PHONY : module01_3.o

# target to build an object file
module01_3.cpp.o:
	$(MAKE) -f CMakeFiles/module01.dir/build.make CMakeFiles/module01.dir/module01_3.cpp.o
.PHONY : module01_3.cpp.o

module01_3.i: module01_3.cpp.i

.PHONY : module01_3.i

# target to preprocess a source file
module01_3.cpp.i:
	$(MAKE) -f CMakeFiles/module01.dir/build.make CMakeFiles/module01.dir/module01_3.cpp.i
.PHONY : module01_3.cpp.i

module01_3.s: module01_3.cpp.s

.PHONY : module01_3.s

# target to generate assembly for a file
module01_3.cpp.s:
	$(MAKE) -f CMakeFiles/module01.dir/build.make CMakeFiles/module01.dir/module01_3.cpp.s
.PHONY : module01_3.cpp.s

module02_1.o: module02_1.cpp.o

.PHONY : module02_1.o

# target to build an object file
module02_1.cpp.o:
	$(MAKE) -f CMakeFiles/module02.dir/build.make CMakeFiles/module02.dir/module02_1.cpp.o
.PHONY : module02_1.cpp.o

module02_1.i: module02_1.cpp.i

.PHONY : module02_1.i

# target to preprocess a source file
module02_1.cpp.i:
	$(MAKE) -f CMakeFiles/module02.dir/build.make CMakeFiles/module02.dir/module02_1.cpp.i
.PHONY : module02_1.cpp.i

module02_1.s: module02_1.cpp.s

.PHONY : module02_1.s

# target to generate assembly for a file
module02_1.cpp.s:
	$(MAKE) -f CMakeFiles/module02.dir/build.make CMakeFiles/module02.dir/module02_1.cpp.s
.PHONY : module02_1.cpp.s

module02_2.o: module02_2.cpp.o

.PHONY : module02_2.o

# target to build an object file
module02_2.cpp.o:
	$(MAKE) -f CMakeFiles/module02.dir/build.make CMakeFiles/module02.dir/module02_2.cpp.o
.PHONY : module02_2.cpp.o

module02_2.i: module02_2.cpp.i

.PHONY : module02_2.i

# target to preprocess a source file
module02_2.cpp.i:
	$(MAKE) -f CMakeFiles/module02.dir/build.make CMakeFiles/module02.dir/module02_2.cpp.i
.PHONY : module02_2.cpp.i

module02_2.s: module02_2.cpp.s

.PHONY : module02_2.s

# target to generate assembly for a file
module02_2.cpp.s:
	$(MAKE) -f CMakeFiles/module02.dir/build.make CMakeFiles/module02.dir/module02_2.cpp.s
.PHONY : module02_2.cpp.s

module02_3.o: module02_3.cpp.o

.PHONY : module02_3.o

# target to build an object file
module02_3.cpp.o:
	$(MAKE) -f CMakeFiles/module02.dir/build.make CMakeFiles/module02.dir/module02_3.cpp.o
.PHONY : module02_3.cpp.o

module02_3.i: module02_3.cpp.i

.PHONY : module02_3.i

# target to preprocess a source file
module02_3.cpp.i:
	$(MAKE) -f CMakeFiles/module02.dir/build.make CMakeFiles/module02.dir/module02_3.cpp.i
.PHONY : module02_3.cpp.i

module02_3.s: module02_3.cpp.s

.PHONY : module02_3.s

# target to generate assembly for a file
module02_3.cpp.s:
	$(MAKE) -f CMakeFiles/module02.dir/build.make CMakeFiles/module02.dir/module02_3.cpp.s
.PHONY : module02_3.cpp.s

module02_4.o: module02_4.cpp.o

.PHONY : module02_4.o

# target to build an object file
module02_4.cpp.o:
	$(MAKE) -f CMakeFiles/module02.dir/build.make CMakeFiles/module02.dir/module02_4.cpp.o
.PHONY : module02_4.cpp.o

module02_4.i: module02_4.cpp.i

.PHONY : module02_4.i

# target to preprocess a source file
module02_4.cpp.i:
	$(MAKE) -f CMakeFiles/module02.dir/build.make CMakeFiles/module02.dir/module02_4.cpp.i
.PHONY : module02_4.cpp.i

module02_4.s: module02_4.cpp.s

.PHONY : module02_4.s

# target to generate assembly for a file
module02_4.cpp.s:
	$(MAKE) -f CMakeFiles/module02.dir/build.make CMakeFiles/module02.dir/module02_4.cpp.s
.PHONY : module02_4.cpp.s

sys/catch_main.o: sys/catch_main.cpp.o

.PHONY : sys/catch_main.o

# target to build an object file
sys/catch_main.cpp.o:
	$(MAKE) -f CMakeFiles/exercise_base.dir/build.make CMakeFiles/exercise_base.dir/sys/catch_main.cpp.o
.PHONY : sys/catch_main.cpp.o

sys/catch_main.i: sys/catch_main.cpp.i

.PHONY : sys/catch_main.i

# target to preprocess a source file
sys/catch_main.cpp.i:
	$(MAKE) -f CMakeFiles/exercise_base.dir/build.make CMakeFiles/exercise_base.dir/sys/catch_main.cpp.i
.PHONY : sys/catch_main.cpp.i

sys/catch_main.s: sys/catch_main.cpp.s

.PHONY : sys/catch_main.s

# target to generate assembly for a file
sys/catch_main.cpp.s:
	$(MAKE) -f CMakeFiles/exercise_base.dir/build.make CMakeFiles/exercise_base.dir/sys/catch_main.cpp.s
.PHONY : sys/catch_main.cpp.s

sys/utilities.o: sys/utilities.cpp.o

.PHONY : sys/utilities.o

# target to build an object file
sys/utilities.cpp.o:
	$(MAKE) -f CMakeFiles/exercise_base.dir/build.make CMakeFiles/exercise_base.dir/sys/utilities.cpp.o
.PHONY : sys/utilities.cpp.o

sys/utilities.i: sys/utilities.cpp.i

.PHONY : sys/utilities.i

# target to preprocess a source file
sys/utilities.cpp.i:
	$(MAKE) -f CMakeFiles/exercise_base.dir/build.make CMakeFiles/exercise_base.dir/sys/utilities.cpp.i
.PHONY : sys/utilities.cpp.i

sys/utilities.s: sys/utilities.cpp.s

.PHONY : sys/utilities.s

# target to generate assembly for a file
sys/utilities.cpp.s:
	$(MAKE) -f CMakeFiles/exercise_base.dir/build.make CMakeFiles/exercise_base.dir/sys/utilities.cpp.s
.PHONY : sys/utilities.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... hello_world"
	@echo "... exercise_base"
	@echo "... module01"
	@echo "... module02"
	@echo "... hello.o"
	@echo "... hello.i"
	@echo "... hello.s"
	@echo "... module01_1.o"
	@echo "... module01_1.i"
	@echo "... module01_1.s"
	@echo "... module01_2.o"
	@echo "... module01_2.i"
	@echo "... module01_2.s"
	@echo "... module01_3.o"
	@echo "... module01_3.i"
	@echo "... module01_3.s"
	@echo "... module02_1.o"
	@echo "... module02_1.i"
	@echo "... module02_1.s"
	@echo "... module02_2.o"
	@echo "... module02_2.i"
	@echo "... module02_2.s"
	@echo "... module02_3.o"
	@echo "... module02_3.i"
	@echo "... module02_3.s"
	@echo "... module02_4.o"
	@echo "... module02_4.i"
	@echo "... module02_4.s"
	@echo "... sys/catch_main.o"
	@echo "... sys/catch_main.i"
	@echo "... sys/catch_main.s"
	@echo "... sys/utilities.o"
	@echo "... sys/utilities.i"
	@echo "... sys/utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

